version: '3.9'

services:

  #pythonApp:

  mariadb:
    container_name: mariadb 
    image: mariadb:10.6.4
    environment:
      MARIADB_USER: "example"
      MARIADB_PASSWORD: "example"
      MARIADB_ROOT_PASSWORD: "example" 
    networks:
      lb_example:
        ipv4_address: 172.28.0.19
        aliases:
          - mariadb
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.3
    environment:
      PMA_HOST: "mariadb"
      MYSQL_ROOT_PASSWORD: "example"
    ports:
      - '8081:80'
    networks:
      lb_example:
        ipv4_address: 172.28.0.30
        aliases:
          - phpmyadmin
    restart: on-failure


networks:
  lb_example:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

# vim:sw=2:ts=2:sts=2:et
